version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://kmjak:kmjak@db:5432/todo

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: kmjak
      POSTGRES_PASSWORD: kmjak
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: